Repository maestro-framework/maestro, pull requests merged in 2020-08, with the labels that each got.

#23 Change README title to Maestro
  README.md
Labels: documentation

#20 Sleep create lambdas
  bin/deploy.js
  src/aws/createLambdaFunctions.js
Labels: enhancement

#30 Read in `region` variable from config file
  src/aws/services.js
Labels: enhancement

#31 Dynamically generate state machine
  src/aws/generateStateMachineParams.js
  state-machines/example-workflow.asl.json
Labels: enhancement

#38 Prepend workflow name to lambdas
  bin/deploy.js
  bin/teardown.js
  src/aws/generateMultipleFunctionParams.js
  src/aws/generateStateMachineParams.js
Labels: enhancement

#49 Create `new` command to create new Maestro project
  README.md
  bin/maestro.js
  src/aws/iam/establishIAMRole.js
  src/commands/deploy.js
  src/commands/newProject.js
  src/util/capitalize.js
  src/util/cleanupProjectName.js
  src/util/configDir.js
  src/util/copyTemplateToDir.js
  src/util/createEmptyProject.js
  src/util/createProjectFromTemplate.js
  src/util/createProjectWithoutTemplate.js
  src/util/initializeGitRepository.js
  src/util/selectTemplateIdx.js
  src/util/titleize.js
Labels: documentation, enhancement, help wanted

#53 [WIP] Add super basic man pages
  .gitignore
  bin/maestro.js
  bin/welcome-message.sh
  bin/zip-man-pages.sh
  doc/man/maestro-config.1
  doc/man/maestro-deploy.1
  doc/man/maestro-get-templates.1
  doc/man/maestro-help.1
  doc/man/maestro-new.1
  doc/man/maestro-teardown.1
  doc/man/maestro.1
  package.json
Labels: documentation, help wanted

#54 Maestro config cmd
  bin/maestro.js
  bin/welcome-message.sh
  src/aws/services.js
  src/aws/step-function/generateStateMachineParams.js
  src/commands/config.js
Labels: enhancement

#60 Replace filesystem operations using `childProcess.execSync`
  src/commands/getTemplates.js
Labels: enhancement

#62 Config command validation
  src/commands/config.js
  src/config/AWSRegions.js
Labels: enhancement

#68 Update src/util/awsAccountInfo.js to conditionally read hidden directory
  src/util/awsAccountInfo.js
Labels: bug

#75 Update `man maestro-config` to include a description
  bin/welcome-message.sh
  bin/zip-man-pages.sh
  doc/man/maestro-config.1
  doc/man/maestro.1
  package.json
Labels: documentation

#78 Initial Unit tests
  package.json
  test/awsAccountInfo.test.js
  test/templates.test.js
Labels: enhancement

#81 Add a colon at the end of all `promptAsync` prompts
  src/util/promptAsync.js
Labels: enhancement
